{{- if .Values.registry.enabled }}

# MARK: ConfigMap 'cora-registry'
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "common.fullname" . }}-registry
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
    app.kubernetes.io/component: registry
data:
  config.yml: |
    version: 0.1
    log:
      # level: debug
      fields:
        service: registry
    # auth:
    #   token:
    #     realm: ""
    #     service: ""
    #     issuer: "Cloud Pipeline"
    #     rootcertbundle: ""
    notifications:
      endpoints:
        - name: tools_notifications
          disabled: false
          headers:
            Authorization: ["Bearer {{ .Values.registry.notificationToken }}"]
            Registry-Path: ["dev-op-registry.merck.com"]  # FIXME: put into vars
          timeout: 1s
          threshold: 5
          backoff: 1s
          ignoredmediatypes:
            - application/octet-stream
            - application/vnd.docker.container.image.rootfs.diff+x-gtar
            - application/vnd.docker.container.distribution.manifest.list.v2+json
            - application/vnd.docker.container.image.v1+json
            - application/vnd.docker.image.rootfs.diff.tar.gzip
            - application/vnd.docker.image.rootfs.foreign.diff.tar.gzip
            - application/vnd.docker.plugin.v1+json
    health:
      storagedriver:
        enabled: true
        interval: 10s
        threshold: 3
    http:
      addr: ":5000"
      debug:
        addr: ":5001"
        prometheus:
          enabled: true
          path: /metrics
    storage:
      cache:
        blobdescriptor: inmemory
      delete:
        enabled: true
      s3:
        secure: true
        v4auth: true
        chunksize: 52428800
        rootdirectory: /docker-pub/

# MARK: Service 'cora-registry'
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "common.fullname" . }}-registry-backend
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
    app.kubernetes.io/component: registry
spec:
  type: ClusterIP
  ports:
    - name: http
      protocol: TCP
      port: 5000
      targetPort: http
    - name: debug
      protocol: TCP
      port: 5001
      targetPort: debug
  selector:
    {{- include "common.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: registry

# MARK: Deployment 'cora-registry'
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "common.fullname" . }}-registry
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
    app.kubernetes.io/component: registry
    # cloud-pipeline/cp-docker-registry: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "common.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: registry
      # cloud-pipeline/cp-docker-registry: "true"
  template:
    metadata:
      annotations:
        checksum/config: {{ .Values.registry.config | toYaml | sha256sum }}
      labels:
        {{- include "common.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: registry
        # cloud-pipeline/cp-docker-registry: "true"
    spec:
      containers:
        - name: registry
          image: "{{ .Values.registry.image.repository }}:{{ .Values.registry.image.tag }}"
          command:
            - /entrypoint.sh
            - /etc/docker/registry/config.yml
          env:
            - name: OTEL_TRACES_EXPORTER
              value: none
          ports:
            - name: http
              protocol: TCP
              containerPort: 5000
            - name: debug
              protocol: TCP
              containerPort: 5001
          resources: {}
          volumeMounts:
            - name: conf
              mountPath: /etc/docker/registry
      securityContext: {}
      tolerations:
        - effect: NoSchedule
          key: node-role.kubernetes.io/master
      volumes:
        - name: conf
          configMap:
            name: {{ include "common.fullname" . }}-registry

{{- end }}
